"""Vector Upserter for writing chunks to vector database.

This module implements the VectorUpserter component, responsible for:
- Transforming chunks and vectors into storage records
- Calling VectorStore for idempotent writes

Design Principles:
- Single Source of Truth: Uses chunk.id generated by DocumentChunker
- Idempotent: Same content produces same ID, repeated writes safe
- Observable: Accepts TraceContext for future integration
- Config-Driven: Uses VectorStoreFactory from settings
- Type-Safe: Full type hints and validation
"""

import hashlib
from typing import List, Dict, Any, Optional

from src.core.types import Chunk
from src.core.settings import Settings
from src.libs.vector_store.vector_store_factory import VectorStoreFactory


class VectorUpserter:
    """Write chunks and vectors to vector database with idempotent guarantees.
    
    This upserter receives chunks and their dense vectors from DenseEncoder,
    generates stable chunk IDs, and writes them to the configured vector store.
    
    Chunk IDs are generated upstream by DocumentChunker and stored on
    ``chunk.id``.  VectorUpserter uses them directly to guarantee a
    single source of truth for ID generation across the pipeline.
    
    Example:
        >>> upserter = VectorUpserter(settings)
        >>> 
        >>> chunks = [
        ...     Chunk(id="temp1", text="Hello world", metadata={"source_path": "doc.pdf", "chunk_index": 0}),
        ...     Chunk(id="temp2", text="Python rocks", metadata={"source_path": "doc.pdf", "chunk_index": 1})
        ... ]
        >>> vectors = [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]]
        >>> 
        >>> upserter.upsert(chunks, vectors)
        >>> # Chunks written with stable IDs like: "a1b2c3d4_0000_e5f6g7h8"
    """
    
    def __init__(self, settings: Settings, collection_name: Optional[str] = None):
        """Initialize VectorUpserter with configured vector store.
        
        Args:
            settings: Application settings containing vector_store configuration.
            collection_name: Optional collection name to override settings default.
        
        Raises:
            ValueError: If settings are invalid or vector store cannot be created.
        """
        self.settings = settings
        kwargs = {}
        if collection_name:
            kwargs['collection_name'] = collection_name
        self.vector_store = VectorStoreFactory.create(settings, **kwargs)

    def _generate_chunk_id(self, chunk: Chunk) -> str:
        """Backward-compatible stable chunk ID generation.

        Runtime production paths already provide chunk IDs upstream via
        ``DocumentChunker``. Some older unit tests still validate the previous
        source-path-based ID scheme directly on ``VectorUpserter``.
        """
        source_path = chunk.metadata.get("source_path")
        if not source_path:
            raise ValueError("Chunk metadata must include source_path")
        if "chunk_index" not in chunk.metadata:
            raise ValueError("Chunk metadata must include chunk_index")

        source_hash = hashlib.sha256(str(source_path).encode("utf-8")).hexdigest()[:8]
        content_hash = hashlib.sha256(chunk.text.encode("utf-8")).hexdigest()[:8]
        chunk_index = int(chunk.metadata["chunk_index"])
        return f"{source_hash}_{chunk_index:04d}_{content_hash}"

    def upsert_batch(
        self,
        batches: List[tuple[List[Chunk], List[List[float]]]],
        trace: Optional[Any] = None,
    ) -> List[str]:
        """Backward-compatible batch helper that flattens multiple batches."""
        if not batches:
            raise ValueError("Cannot upsert empty batches")

        chunks: List[Chunk] = []
        vectors: List[List[float]] = []
        for batch_chunks, batch_vectors in batches:
            chunks.extend(batch_chunks)
            vectors.extend(batch_vectors)
        return self.upsert(chunks, vectors, trace=trace)
    
    def upsert(
        self,
        chunks: List[Chunk],
        vectors: List[List[float]],
        trace: Optional[Any] = None,
    ) -> List[str]:
        """Upsert chunks with their vectors to vector store.
        
        Args:
            chunks: List of Chunk objects to store.
            vectors: List of embedding vectors (same order and length as chunks).
            trace: Optional TraceContext for observability (reserved for Stage F).
        
        Returns:
            List of generated chunk IDs (same order as input chunks).
        
        Raises:
            ValueError: If chunks and vectors lengths don't match, or if required
                       metadata fields are missing.
            RuntimeError: If vector store upsert operation fails.
        
        Example:
            >>> chunks = [Chunk(...), Chunk(...)]
            >>> vectors = [[0.1, 0.2], [0.3, 0.4]]
            >>> chunk_ids = upserter.upsert(chunks, vectors)
            >>> len(chunk_ids) == len(chunks)  # True
        """
        # Validate input lengths match
        if len(chunks) != len(vectors):
            raise ValueError(
                f"Chunk count ({len(chunks)}) must match vector count ({len(vectors)})"
            )
        
        if not chunks:
            raise ValueError("Cannot upsert empty chunks list")
        
        records = []
        chunk_ids = []
        
        for chunk, vector in zip(chunks, vectors):
            chunk_id = chunk.id
            chunk_ids.append(chunk_id)
            
            record = {
                "id": chunk_id,
                "vector": vector,
                "metadata": {
                    **chunk.metadata,
                    "text": chunk.text,
                    "chunk_id": chunk_id,
                },
            }
            records.append(record)
        
        # Perform idempotent upsert
        try:
            self.vector_store.upsert(records, trace=trace)
        except Exception as e:
            raise RuntimeError(
                f"Vector store upsert failed: {str(e)}"
            ) from e
        
        return chunk_ids
    
