source_groups:
  "第1章 计算机网络与因特网.pptx":
    - "第1章 计算机网络与因特网.pptx"
    - "计算机网络（第8版）_谢希仁_上半.pdf"
    - "计算机网络（第8版）_谢希仁_下半.pdf"
    - "《计算机网络》2022-计算汇编_word版_缺失5-16..docx"
  "第2章 应用层.pptx":
    - "第2章 应用层.pptx"
    - "计算机网络（第8版）_谢希仁_上半.pdf"
    - "计算机网络（第8版）_谢希仁_下半.pdf"
    - "《计算机网络》2022-计算汇编_word版_缺失5-16..docx"
  "第3章 运输层.pptx":
    - "第3章 运输层.pptx"
    - "计算机网络（第8版）_谢希仁_上半.pdf"
    - "计算机网络（第8版）_谢希仁_下半.pdf"
    - "《计算机网络》2022-计算汇编_word版_缺失5-16..docx"
  "第4章 网络层.pptx":
    - "第4章 网络层.pptx"
    - "计算机网络（第8版）_谢希仁_上半.pdf"
    - "计算机网络（第8版）_谢希仁_下半.pdf"
    - "《计算机网络》2022-计算汇编_word版_缺失5-16..docx"
  "第6章 链路层和局域网.pptx":
    - "第6章 链路层和局域网.pptx"
    - "计算机网络（第8版）_谢希仁_上半.pdf"
    - "计算机网络（第8版）_谢希仁_下半.pdf"
    - "《计算机网络》2022-计算汇编_word版_缺失5-16..docx"
